In [1]:
import pandas as pd

In [2]:
expansion_dates_df = pd.read_csv("medicaid_data/medicaid_expansion_dates.csv")
expansion_dates_df

                   State             Expansion Status Date Implemented
0                Alabama                  Not Adopted              NaN
1                 Alaska      Adopted and Implemented         9/1/2015
2                Arizona      Adopted and Implemented         1/1/2014
3               Arkansas      Adopted and Implemented         1/1/2014
4             California      Adopted and Implemented         1/1/2014
5               Colorado      Adopted and Implemented         1/1/2014
6            Connecticut      Adopted and Implemented         1/1/2014
7               Delaware      Adopted and Implemented         1/1/2014
8   District of Columbia      Adopted and Implemented         1/1/2014
9                Florida                  Not Adopted              NaN
10               Georgia                  Not Adopted              NaN
11                Hawaii      Adopted and Implemented         1/1/2014
12                 Idaho      Adopted and Implemented         1/1/2020
13              Illinois      Adopted and Implemented         1/1/2014
14               Indiana      Adopted and Implemented         2/1/2015
15                  Iowa      Adopted and Implemented         1/1/2014
16                Kansas                  Not Adopted              NaN
17              Kentucky      Adopted and Implemented         1/1/2014
18             Louisiana      Adopted and Implemented         7/1/2016
19                 Maine      Adopted and Implemented        1/10/2019
20              Maryland      Adopted and Implemented         1/1/2014
21         Massachusetts      Adopted and Implemented         1/1/2014
22              Michigan      Adopted and Implemented         4/1/2014
23             Minnesota      Adopted and Implemented         1/1/2014
24           Mississippi                  Not Adopted              NaN
25              Missouri  Adopted but Not Implemented         7/1/2021
26               Montana      Adopted and Implemented         1/1/2016
27              Nebraska      Adopted and Implemented        10/1/2020
28                Nevada      Adopted and Implemented         1/1/2014
29         New Hampshire      Adopted and Implemented        8/15/2014
30            New Jersey      Adopted and Implemented         1/1/2014
31            New Mexico      Adopted and Implemented         1/1/2014
32              New York      Adopted and Implemented         1/1/2014
33        North Carolina                  Not Adopted              NaN
34          North Dakota      Adopted and Implemented         1/1/2014
35                  Ohio      Adopted and Implemented         1/1/2014
36              Oklahoma  Adopted but Not Implemented         7/1/2021
37                Oregon      Adopted and Implemented         1/1/2014
38          Pennsylvania      Adopted and Implemented         1/1/2015
39          Rhode Island      Adopted and Implemented         1/1/2014
40        South Carolina                  Not Adopted              NaN
41          South Dakota                  Not Adopted              NaN
42             Tennessee                  Not Adopted              NaN
43                 Texas                  Not Adopted              NaN
44                  Utah      Adopted and Implemented         1/1/2020
45               Vermont      Adopted and Implemented         1/1/2014
46              Virginia      Adopted and Implemented         1/1/2019
47            Washington      Adopted and Implemented         1/1/2014
48         West Virginia      Adopted and Implemented         1/1/2014
49             Wisconsin                  Not Adopted              NaN
50               Wyoming                  Not Adopted              NaN

In [3]:
enrollment_changes_df = pd.read_csv("medicaid_data/medicaid_expansion_enrollment_changes.csv")
enrollment_changes_df
## state data ends after row 53

,Location,Pre-ACA Average Monthly Enrollment,Total Monthly Medicaid/CHIP Enrollment,Percent Change,Footnotes
0,United States,56511799.0,76489912.0,0.333527,1.0
1,Alabama,799176.0,972314.0,0.216646,2.0
2,Alaska,122334.0,234622.0,0.917881,NaN
3,Arizona,1201770.0,1887382.0,0.570502,NaN
4,Arkansas,556851.0,844592.0,0.516729,NaN
...,...,...,...,...,...
87,8. Oregon's Pre-ACA Average Monthly Enrollment...,NaN,NaN,NaN,NaN
88,9. Utah data includes individuals enrolled in ...,NaN,NaN,NaN,NaN
89,10. Washington data includes individuals enrol...,NaN,NaN,NaN,NaN
90,11. West Virginia data includes individuals en...,NaN,NaN,NaN,NaN
91,12. Wisconsin's Pre-ACA Average Monthly Enroll...,NaN,NaN,NaN,NaN

In [4]:
enrollment_data_df = pd.read_csv("medicaid_data/2019_01_Preliminary_applications__eligibility_determinations__and_enrollment_data.csv")
enrollment_data_df

,State Abbreviation,State Name,Report Date,State Expanded Medicaid,Preliminary_Updated,Final_Report,New Applications Submitted to Medicaid and CHIP Agencies,New Applications Submitted to Medicaid and CHIP Agencies – footnotes,Applications for Financial Assistance Submitted to the State Based Marketplace,Applications for Financial Assistance Submitted to the State Based Marketplace – footnotes,...,Medicaid and CHIP Child Enrollment - footnotes,Total Medicaid and CHIP Enrollment,Total Medicaid and CHIP Enrollment - footnotes,Latitude,Longitude,New Georeferenced Column,Total Medicaid Enrollment,Total Medicaid Enrollment - footnotes,Total CHIP Enrollment,Total CHIP Enrollment - footnotes
0,CT,Connecticut,1/1/2019,Y,P,N,"5,294",Includes Duplicates,13976.0,Includes Duplicates; Includes Renewals and/or ...,...,NaN,"861,977",NaN,39.0646,-105.3272,"(39.0646, -105.3272)",841860,NaN,20117,NaN
1,TN,Tennessee,1/1/2019,N,P,N,NaN,NaN,NaN,NaN,...,NaN,"1,396,023",NaN,41.6772,-71.5101,"(41.6772, -71.5101)",1344033,NaN,51990,NaN
2,MD,Maryland,1/1/2019,Y,P,N,"7,860",NaN,100608.0,Includes Renewals and/or Redeterminations,...,NaN,"1,298,973",NaN,42.2373,-71.5314,"(42.2373, -71.5314)",1142611,NaN,156362,NaN
3,NV,Nevada,1/1/2019,Y,P,N,"20,134",Includes Renewals and/or Redeterminations,NaN,NaN,...,NaN,"635,194",NaN,40.3140,-74.5089,"(40.314, -74.5089)",593290,NaN,41904,NaN
4,WY,Wyoming,1/1/2019,N,P,N,"1,627",Does Not Include All Medicaid Applications Sub...,NaN,NaN,...,NaN,"56,276",NaN,44.0407,-72.7093,"(44.0407, -72.7093)",51778,NaN,4498,NaN
5,MN,Minnesota,1/1/2019,Y,P,N,"4,790",NaN,31053.0,NaN,...,NaN,"1,037,867",NaN,43.3504,-84.5603,"(43.3504, -84.5603)",1036809,NaN,1058,NaN
6,WA,Washington,1/1/2019,Y,P,N,"72,242",NaN,80022.0,NaN,...,Includes Individuals Enrolled At Any Time in M...,"1,731,888",Includes Individuals Enrolled At Any Time in M...,40.1135,-111.8535,"(40.1135, -111.8535)",1661475,Includes Individuals Enrolled At Any Time in M...,70413,NaN
7,CA,California,1/1/2019,Y,P,N,"236,381",Does Not Include All Medicaid Applications Sub...,NaN,NaN,...,NaN,"11,823,859",NaN,33.7712,-111.3877,"(33.7712, -111.3877)",10530288,NaN,1293571,NaN
8,CO,Colorado,1/1/2019,Y,P,N,"28,392",NaN,214.0,NaN,...,NaN,"1,321,099",NaN,36.1700,-119.7462,"(36.17, -119.7462)",1239246,NaN,81853,NaN
9,ID,Idaho,1/1/2019,Y,P,N,"10,852",NaN,NaN,NaN,...,NaN,"266,351",NaN,42.0046,-93.2140,"(42.0046, -93.214)",239712,NaN,26639,NaN
10,LA,Louisiana,1/1/2019,Y,P,N,"31,532",NaN,NaN,NaN,...,NaN,"1,592,641",NaN,37.6690,-84.6514,"(37.669, -84.6514)",1458967,NaN,133674,NaN
11,AR,Arkansas,1/1/2019,Y,P,N,"22,763",NaN,NaN,NaN,...,NaN,"790,753",NaN,34.9513,-92.3809,"(34.9513, -92.3809)",760071,NaN,30682,NaN
12,KY,Kentucky,1/1/2019,Y,P,N,"11,377",NaN,NaN,NaN,...,NaN,"1,314,498",NaN,38.5111,-96.8005,"(38.5111, -96.8005)",1221140,NaN,93358,NaN
13,NJ,New Jersey,1/1/2019,Y,P,N,"54,916",Does Not Include All Non-MAGI Applications Sub...,NaN,NaN,...,NaN,"1,703,032",NaN,41.1289,-98.2883,"(41.1289, -98.2883)",1492517,NaN,210515,NaN
14,OR,Oregon,1/1/2019,Y,P,N,"13,850",Does Not Include All Non-MAGI Applications Sub...,NaN,NaN,...,NaN,"971,345",NaN,40.3736,-82.7755,"(40.3736, -82.7755)",846069,NaN,125276,NaN
15,ME,Maine,1/1/2019,Y,P,N,"9,522",NaN,NaN,NaN,...,NaN,"226,429",NaN,39.0724,-76.7902,"(39.0724, -76.7902)",215148,NaN,11281,NaN
16,VA,Virginia,1/1/2019,Y,P,N,"37,416",Includes Renewals and/or Redeterminations,NaN,NaN,...,NaN,"1,237,262",NaN,35.7449,-86.7489,"(35.7449, -86.7489)",1095021,NaN,142241,NaN
17,AL,Alabama,1/1/2019,N,P,N,"20,505",NaN,NaN,NaN,...,NaN,"899,349",NaN,32.7990,-86.8073,"(32.799, -86.8073)",730349,NaN,169000,NaN
18,DC,District of Columbia,1/1/2019,Y,P,N,"1,809",Includes SBM data,2036.0,NaN,...,NaN,"253,744",NaN,41.5834,-72.7622,"(41.5834, -72.7622)",237337,NaN,16407,NaN
19,ND,North Dakota,1/1/2019,Y,P,N,"2,187",NaN,NaN,NaN,...,NaN,"91,060",NaN,46.9048,-110.3261,"(46.9048, -110.3261)",88885,NaN,2175,NaN
20,TX,Texas,1/1/2019,N,P,N,"131,871",NaN,NaN,NaN,...,NaN,"4,277,703",NaN,33.8191,-80.9066,"(33.8191, -80.9066)",3631572,NaN,646131,NaN
21,HI,Hawaii,1/1/2019,Y,P,N,"5,248",NaN,NaN,NaN,...,NaN,"330,244",NaN,32.9866,-83.6487,"(32.9866, -83.6487)",304970,NaN,25274,NaN
22,WV,West Virginia,1/1/2019,Y,P,N,"28,185",NaN,NaN,NaN,...,Includes Individuals Enrolled At Any Time in M...,"520,219",Includes Individuals Enrolled At Any Time in M...,18.0001,-64.8199,"(18.0001, -64.8199)",486589,Includes Individuals Enrolled At Any Time in M...,33630,Includes Individuals Enrolled At Any Time in M...
23,NC,North Carolina,1/1/2019,N,P,N,"23,960",NaN,NaN,NaN,...,NaN,"1,754,020",NaN,32.7673,-89.6812,"(32.7673, -89.6812)",1495121,NaN,258899,NaN
24,IL,Illinois,1/1/2019,Y,P,N,"64,477",NaN,NaN,NaN,...,NaN,"2,817,556",NaN,44.2394,-114.5103,"(44.2394, -114.5103)",2564139,NaN,253417,NaN
25,NE,Nebraska,1/1/2019,N,P,N,"6,957",NaN,NaN,NaN,...,NaN,"242,385",NaN,35.6411,-79.8431,"(35.6411, -79.8431)",207740,NaN,34645,NaN
26,PA,Pennsylvania,1/1/2019,Y,P,N,"83,047",Includes Renewals and/or Redeterminations,NaN,NaN,...,NaN,"2,938,407",NaN,35.5376,-96.9247,"(35.5376, -96.9247)",2757505,NaN,180902,NaN
27,SD,South Dakota,1/1/2019,N,P,N,"2,801",Includes Accounts Transferred from FFM; Does N...,NaN,NaN,...,NaN,"111,178",NaN,18.2766,-66.3350,"(18.2766, -66.335)",95120,NaN,16058,NaN
28,KS,Kansas,1/1/2019,N,P,N,NaN,NaN,NaN,NaN,...,NaN,"390,420",NaN,39.8647,-86.2604,"(39.8647, -86.2604)",334248,NaN,56172,NaN
29,NY,New York,1/1/2019,Y,P,N,NaN,NaN,766142.0,NaN,...,Includes Retroactive Enrollments,"6,138,367",Includes Retroactive Enrollments,34.8375,-106.2371,"(34.8375, -106.2371)",5569916,Includes Retroactive Enrollments,568451,NaN
30,OK,Oklahoma,1/1/2019,N,P,N,"53,653",Includes Renewals and/or Redeterminations,NaN,NaN,...,NaN,"730,160",NaN,42.1497,-74.9384,"(42.1497, -74.9384)",608692,NaN,121468,NaN
31,AK,Alaska,1/1/2019,Y,P,N,"3,472",Includes Renewals and/or Redeterminations,NaN,NaN,...,NaN,"214,541",NaN,61.3850,-152.2683,"(61.385, -152.2683)",199656,NaN,14885,NaN
32,GA,Georgia,1/1/2019,N,P,N,"45,292",NaN,NaN,NaN,...,NaN,"1,798,195",NaN,27.8333,-81.7170,"(27.8333, -81.717)",1588271,NaN,209924,NaN
33,NH,New Hampshire,1/1/2019,Y,P,N,"9,613",NaN,NaN,NaN,...,NaN,"181,293",NaN,47.5362,-99.7930,"(47.5362, -99.793)",166181,NaN,15112,NaN
34,RI,Rhode Island,1/1/2019,Y,P,N,"2,348","Includes Applications for Other Programs (e.g,...",NaN,NaN,...,NaN,"308,844",NaN,44.5672,-122.1269,"(44.5672, -122.1269)",275859,NaN,32985,NaN
35,MT,Montana,1/1/2019,Y,P,N,"3,745",NaN,NaN,NaN,...,NaN,"277,633",NaN,14.8058,145.5505,"(14.8058, 145.5505)",248733,NaN,28900,NaN
36,WI,Wisconsin,1/1/2019,N,P,N,"23,830",Does Not Include All Applications for Limited-...,NaN,NaN,...,NaN,"1,021,451",NaN,37.7680,-78.2057,"(37.768, -78.2057)",950778,NaN,70673,NaN
37,IN,Indiana,1/1/2019,Y,P,N,"98,151",NaN,NaN,NaN,...,NaN,"1,443,002",NaN,40.3363,-89.0022,"(40.3363, -89.0022)",1331698,NaN,111304,NaN
38,MO,Missouri,1/1/2019,N,P,N,"21,700",NaN,NaN,NaN,...,NaN,"887,297",NaN,45.7326,-93.9196,"(45.7326, -93.9196)",855629,NaN,31668,Does Not Include All CHIP enrollees
39,VT,Vermont,1/1/2019,Y,P,N,"3,230",NaN,1197.0,NaN,...,NaN,"157,518",NaN,31.1060,-97.6475,"(31.106, -97.6475)",152931,NaN,4587,NaN
40,NM,New Mexico,1/1/2019,Y,P,Y,"13,009",NaN,NaN,NaN,...,Includes Limited-Benefit Enrollees,"729,051",Includes Limited-Benefit Enrollees,43.4108,-71.5653,"(43.4108, -71.5653)",691836,Includes Limited-Benefit Enrollees,37215,NaN
41,MA,Massachusetts,1/1/2019,Y,P,N,"19,372",NaN,3549.0,NaN,...,NaN,"1,531,871",NaN,31.1801,-91.8749,"(31.1801, -91.8749)",1355197,NaN,176674,NaN
42,MI,Michigan,1/1/2019,Y,P,N,"50,653",NaN,NaN,NaN,...,Does Not Include All Full-Benefit Child Medica...,"2,309,960",Does Not Include All Full-Benefit Medicaid enr...,44.6074,-69.3977,"(44.6074, -69.3977)",2248618,Does Not Include All Full-Benefit Medicaid enr...,61342,NaN
43,AZ,Arizona,1/1/2019,Y,P,N,"112,351",NaN,NaN,NaN,...,NaN,"1,701,450",NaN,14.2417,-170.7197,"(14.2417, -170.7197)",1597610,NaN,103840,NaN
44,UT,Utah,1/1/2019,N,P,N,"20,625","Includes Applications for Other Programs (e.g,...",NaN,NaN,...,NaN,"284,808",Includes Enrollees in Other Financial Assistan...,44.2853,-99.4632,"(44.2853, -99.4632)",241719,Includes Enrollees in Other Financial Assistan...,43089,NaN
45,SC,South Carolina,1/1/2019,N,P,N,"25,718",NaN,NaN,NaN,...,NaN,"1,028,077",NaN,40.5773,-77.2640,"(40.5773, -77.264)",939171,NaN,88906,NaN
46,OH,Ohio,1/1/2019,Y,P,N,"73,453",Includes Renewals and/or Redeterminations,NaN,NaN,...,NaN,"2,650,556",NaN,38.4199,-117.1219,"(38.4199, -117.1219)",2444359,NaN,206197,NaN
47,DE,Delaware,1/1/2019,Y,P,N,"3,059",NaN,NaN,NaN,...,NaN,"232,614",NaN,38.8964,-77.0262,"(38.8964, -77.0262)",221080,NaN,11534,NaN
48,FL,Florida,1/1/2019,N,P,N,"333,583",Includes Accounts Transferred from FFM; Does N...,NaN,NaN,...,NaN,"3,679,990",NaN,39.3498,-75.5148,"(39.3498, -75.5148)",3450613,NaN,229377,NaN
49,IA,Iowa,1/1/2019,Y,P,N,"14,666",Includes Renewals and/or Redeterminations; Inc...,NaN,NaN,...,NaN,"683,137",NaN,21.1098,-157.5311,"(21.1098, -157.5311)",611840,NaN,71297,NaN
50,MS,Mississippi,1/1/2019,N,P,N,"20,402",NaN,NaN,NaN,...,NaN,"611,749",NaN,38.4623,-92.3020,"(38.4623, -92.302)",536319,NaN,75430,NaN