In [79]:
import pandas as pd

In [80]:
median_income_df = pd.read_csv('income_and_spending_data/median_income_2018.csv')

expansion_dates_df = pd.read_csv("medicaid_data/medicaid_expansion_dates.csv")



state_spending_df = pd.read_csv('income_and_spending_data/usgs_state_2018.csv')




expansion_dates_df = expansion_dates_df.rename(columns={"Date Implemented":"Date Added"})
expansion_dates_df = expansion_dates_df.rename(columns={"State":"State"})

expansion_dates_df

median_income_df = median_income_df.rename(columns={"State ":"State"})
median_income_df


state_spending_df = state_spending_df.rename(columns={"Comparison of State and Local Government Spending":"State"})
state_spending_df = state_spending_df.drop([0,1,2,3,4,13])
state_spending_df = state_spending_df.rename(columns={"Unnamed: 1":"State Spending", "Unnamed: 2":"Local Spending", "Unnamed: 3":"State and Local Spending", "Unnamed: 4":"Gross State Product", "Unnamed: 5":"Real State Growth Percentage", "Unnamed: 6":"Population (Millions)"})
state_spending_df

,State,State Spending,Local Spending,State and Local Spending,Gross State Product,Real State Growth Percentage,Population (Millions)
5,Alabama,"9,338.30","4,187.10","13,525.40","221,736.00",2.8,4.9
6,Alaska,"2,369.00",495.5,"2,864.50","54,734.10",0.7,0.7
7,Arizona,"12,201.60","1,007.80","13,209.40","348,297.00",4.1,7.2
8,Arkansas,"7,609.90",296.8,"7,906.70","128,419.00",1.7,3
9,California,"123,022.70","39,815.00","162,837.70","2,997,730.00",4.3,39.5
10,Colorado,"9,687.90","2,145.90","11,833.80","371,750.00",3.5,5.7
11,Connecticut,"4,980.40",150.7,"5,131.00","275,727.00",0.5,3.6
12,Delaware,"2,909.10",39.5,"2,948.70","73,481.30",0,1
14,Florida,"31,167.60","10,498.90","41,666.50","1,039,240.00",3.2,21.2
15,Georgia,"13,648.60","5,112.20","18,760.80","592,153.00",2.4,10.5
16,Hawaii,"3,519.80",39.2,"3,559.00","93,797.90",2.4,1.4
17,Idaho,"2,502.00",803.6,"3,305.60","77,052.00",4,1.8
18,Illinois,"21,792.50","3,220.80","25,013.30","865,310.00",2.1,12.7
19,Indiana,"13,199.90","4,790.20","17,990.10","366,800.00",2,6.7
20,Iowa,"7,766.50","2,310.50","10,077.00","189,702.00",2.2,3.1
21,Kansas,"6,577.40","1,176.90","7,754.40","168,318.00",2.1,2.9
22,Kentucky,"13,139.60","1,108.20","14,247.80","208,088.00",1.4,4.5
23,Louisiana,"12,184.70","2,737.00","14,921.60","257,288.00",2.6,4.7
24,Maine,"2,698.80",157.7,"2,856.50","64,856.00",2.2,1.3
25,Maryland,"12,404.70",589.4,"12,994.10","412,584.00",2.5,6
26,Massachusetts,"23,745.70","1,076.70","24,822.30","569,488.00",3.1,6.9
27,Michigan,"19,311.20","3,717.50","23,028.70","527,096.00",2.5,10
28,Minnesota,"14,343.30","2,875.10","17,218.40","368,852.00",2.6,5.6
29,Mississippi,"7,620.60","2,647.50","10,268.10","114,834.00",1.3,3
30,Missouri,"13,673.80","2,358.40","16,032.20","318,921.00",2.4,6.1
31,Montana,"2,343.10",251.1,"2,594.20","50,326.60",2.6,1.1
32,Nebraska,"2,477.20",755.8,"3,233.00","123,978.00",0.9,1.9
33,Nevada,"4,010.70","1,054.70","5,065.40","169,310.00",4.2,3
34,New Hampshire,"2,029.60",24.9,"2,054.50","84,463.90",2.3,1.4
35,New Jersey,"19,769.40",702.8,"20,472.20","622,003.00",2.2,8.9
36,New Mexico,"7,335.40",343.7,"7,679.10","100,297.00",2.5,2.1
37,New York,"71,940.60","16,192.50","88,133.10","1,668,870.00",1.2,19.5
38,North Carolina,"16,786.20","11,540.60","28,326.90","563,690.00",2.4,10.4
39,North Dakota,"1,411.10",69.5,"1,480.60","56,082.30",3.6,0.8
40,Ohio,"29,660.30","3,857.20","33,517.40","675,905.00",1.9,11.7
41,Oklahoma,"6,631.30","1,307.80","7,939.10","202,554.00",2.6,3.9
42,Oregon,"10,067.00","1,367.20","11,434.30","239,783.00",3.8,4.2
43,Pennsylvania,"31,587.60","4,101.20","35,688.80","783,168.00",2.6,12.8
44,Rhode Island,"3,152.80",20.3,"3,173.10","60,587.60",1.2,1.1
45,South Carolina,"10,274.80","5,169.10","15,443.90","233,930.00",2.6,5.1
46,South Dakota,998.5,143.2,"1,141.70","52,014.90",1.9,0.9
47,Tennessee,"11,117.90","4,161.00","15,278.90","364,105.00",3.1,6.8
48,Texas,"43,925.20","15,505.50","59,430.70","1,802,510.00",4,28.6
49,All states combined,"724,840.10","173,350.00","898,190.10","20,580,200.00",2.9,326.7
50,Utah,"5,512.10",806.9,"6,319.00","178,138.00",3.7,3.2
51,Vermont,"1,526.60",9.7,"1,536.30","33,256.30",1.2,0.6
52,Virginia,"16,593.80","1,692.90","18,286.70","532,892.00",2.6,8.5
53,Washington,"16,549.10","5,001.30","21,550.40","565,831.00",5.8,7.5
54,West Virginia,"4,273.60",377.5,"4,651.20","77,437.60",2.3,1.8
55,Wisconsin,"12,390.40","1,180.20","13,570.60","336,294.00",2.4,5.8
56,Wyoming,"1,060.10","1,236.90","2,297.00","39,118.50",0.1,0.6

In [81]:
#df1.merge(df2, how='inner', on='a')
state_data3 = expansion_dates_df.merge(median_income_df, how='inner', on="State")
state_data2 = state_data3.merge(state_spending_df, how='inner', on="State" )
state_data