In [4]:
import pandas as pd

In [6]:
median_income_df = pd.read_csv('income_and_spending_data/median_income_2018.csv')

In [7]:
median_income_df

            State  Median Income Standard Error
0    United States        63,179            420
1          Alabama        49,936          2,423
2           Alaska        68,734          3,390
3          Arizona        62,283          2,291
4         Arkansas        49,781          2,108
5       California        70,489          1,233
6         Colorado        73,034          3,562
7      Connecticut        72,812          5,119
8         Delaware        65,012          3,599
9             D.C.        85,750          2,659
10         Florida        54,644          1,887
11         Georgia        55,821          2,032
12          Hawaii        80,108          3,482
13           Idaho        58,728          2,405
14        Illinois        70,145          2,253
15         Indiana        59,892          1,997
16            Iowa        68,718          2,910
17          Kansas        63,938          2,027
18        Kentucky        54,555          3,668
19       Louisiana        49,973          1,754
20           Maine        58,663          5,683
21        Maryland        86,223          3,331
22   Massachusetts        86,345          2,785
23        Michigan        60,449          1,906
24       Minnesota        71,817          3,656
25     Mississippi        42,781          2,304
26        Missouri        61,726          2,442
27         Montana        57,679          2,876
28        Nebraska        67,575          3,933
29          Nevada        61,864          2,116
30   New Hampshire        81,346          3,394
31      New Jersey        74,176          2,845
32      New Mexico        48,283          2,202
33        New York        67,274          1,722
34  North Carolina        53,369          1,761
35    North Dakota        66,505          3,095
36            Ohio        61,633          2,254
37        Oklahoma        54,434          2,774
38          Oregon        69,165          3,655
39    Pennsylvania        64,524          1,635
40    Rhode Island        62,266          3,348
41  South Carolina        57,444          2,082
42    South Dakota        59,463          2,642
43       Tennessee        56,060          1,442
44           Texas        59,785          1,372
45            Utah        77,067          2,327
46         Vermont        70,066          2,350
47        Virginia        77,151          3,086
48      Washington        79,726          3,025
49   West Virginia        50,573          1,337
50       Wisconsin        62,629          2,039
51         Wyoming        62,539          3,892